---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keerthi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uber
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: keerthisvc
spec:
  type: NodePort
  selector:
    app: uber
  ports:
    - port: 80
      targetPort: 80
